name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for CI/CD

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd my-app
          npm install

      - name: Start Application in Background
        run: |
          cd my-app
          npm start &
          sleep 10  # Give some time for the app to start

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Robot Framework Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-datadriver[excel] openpyxl

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromedriver

      - name: Run Robot Framework Tests in Headless Mode
        run: |
          cd Robot_tests
          robot -d results --variable BROWSER:headlesschrome .

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: Robot_tests/results/